#!/bin/bash
set -eu

vendors_js="
  jquery
  moment
  react
  react-dom
  react-router
"

vendors_css="
  fontawesome
"

function build_vendors() {
  local file_type=$1
  local vendors=$2
  pwd
  cd assets/$file_type

  files=""
  for name in $vendors; do
    files="$files $name.min.$file_type"
  done

  if [[ $file_type == "js" ]]; then
    cat $files > vendors.min.js
  elif [[ $file_type == "css" ]]; then
    cat $files > vendors.min.css
  else
    echo "only js or css files"
    exit 1
  fi

  rm -f ../dev/vendors.min.$file_type
  mv -f vendors.min.$file_type ../../dev/
  cd ../../
}

build_vendors js "$vendors_js"
build_vendors css "$vendors_css"

echo -e "\033[1;32m Success! \033[m"
